variables:
  APP_TEST_NAME: "sc-imaging-app-test-${CI_COMMIT_SHA}"
  CONTAINER_TEST_NAME: "sc-imaging-container-test-${CI_COMMIT_SHA}"
  IMAGE_NAME: "shakecast/imaging:${CI_COMMIT_SHA}"

stages:
  - build
  - test
  - publish
  - cleanup

.docker-connect:
  tags:
    - dev
  before_script:
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" $DOCKER_HUB
  after_script:
    - docker logout

container-build:
  stage: build
  tags:
    - dev
  script:
    - docker build . -t $IMAGE_NAME

app-test:
  stage: test
  tags:
    - dev
  script:
    - docker run -d --rm --name $APP_TEST_NAME $IMAGE_NAME
    - sleep 10
    - docker exec $APP_TEST_NAME python -m shakecastimaging.tests

container-test:
  stage: test
  tags:
    - dev
  script:
    - docker run -d --rm --name $CONTAINER_TEST_NAME $IMAGE_NAME
    - sleep 10
    - docker exec $CONTAINER_TEST_NAME curl localhost:5000

publish-dev:
  stage: publish
  extends: .docker-connect
  only:
    - master
  script:
    - docker build . -t shakecast/imaging:dev
    - docker push shakecast/imaging:dev

publish-prod:
  stage: publish
  extends: .docker-connect
  only:
    - tags
  script:
    - docker build . -t shakecast/imaging:latest
    - docker push shakecast/imaging:latest

cleanup:
  stage: cleanup
  tags:
    - dev
  when: always
  script:
    - docker stop $APP_TEST_NAME || true
    - docker stop $CONTAINER_TEST_NAME || true
    - docker rmi $IMAGE_NAME || true
    - docker rmi shakecast/imaging:dev || true
    - docker rmi shakecast/imaging:latest || true
