variables:
  IMAGE_NAME: "shakecast/imaging:${CI_PIPELINE_ID}"

stages:
  - build
  - test
  - publish
  - cleanup

.docker-connect:
  tags:
    - development
  before_script:
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" $DOCKER_HUB
  after_script:
    - docker logout

.build-container:
  tags:
    - development
  before_script:
    - docker build . -t $IMAGE_NAME-${CI_JOB_ID}
    - docker run -d --rm --name ${CI_JOB_NAME}-${CI_PIPELINE_ID} $IMAGE_NAME-${CI_JOB_ID}
    - sleep 10
  after_script:
    - docker stop ${CI_JOB_NAME}-${CI_PIPELINE_ID}
    - docker rmi $IMAGE_NAME-${CI_JOB_ID}

app-test:
  stage: test
  extends: .build-container
  script:
    - docker exec ${CI_JOB_NAME}-${CI_PIPELINE_ID} python -m shakecastimaging.tests

container-test:
  stage: test
  extends: .build-container
  script:
    - docker exec ${CI_JOB_NAME}-${CI_PIPELINE_ID} curl localhost:5000

publish-dev:
  stage: publish
  extends: .docker-connect
  only:
    - master
  except:
    - schedules
  script:
    - docker build . -t shakecast/imaging:dev
    - docker push shakecast/imaging:dev
  after_script:
    - docker rmi shakecast/imaging:dev

publish-prod:
  stage: publish
  extends: .docker-connect
  only:
    - tags
  script:
    - docker build . -t shakecast/imaging:latest
    - docker push shakecast/imaging:latest
  after_script:
    - docker rmi shakecast/imaging:latest
