stages:
  - build
  - test

container:
  stage: build
  script:
    - docker build . -t shakecast/imaging
    - docker run -p 5000:5000 shakecast/imaging

test:
  stage: test
  tags:
    - dev
  script:
    - apt-get install -y python-pip
    - pip install -r requirements.txt
    - python -m shakecastimaging.tests
