stages:
  - build
  - test
  - deploy
  - cleanup

.docker-connect:
  tags:
    - dev
  before_script:
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" $DOCKER_HUB
  after_script:
    - docker logout

container-build:
  stage: build
  tags:
    - dev
  script:
    - docker build . -t shakecast/imaging

app-test:
  stage: test
  tags:
    - dev
  script:
    - docker run -d --rm --name sc-imaging-app-test shakecast/imaging
    - sleep 10
    - docker exec sc-imaging-app-test python -m shakecastimaging.tests
  
container-test:
  stage: test
  tags:
    - dev
  script:
    - docker run -d --rm --name sc-imaging-container-test shakecast/imaging
    - sleep 10
    - docker exec sc-imaging-container-test curl localhost:5000

deploy-dev:
  stage: deploy
  extends: .docker-connect
  only:
    - master
  script:
    - docker build . -t shakecast/imaging:dev
    - docker push shakecast/imaging:dev

deploy-prod:
  stage: deploy
  extends: .docker-connect
  only:
    - tags
  script:
    - docker build . -t shakecast/imaging:latest
    - docker push shakecast/imaging

cleanup:
  stage: cleanup
  tags:
    - dev
  when: always
  script:
    - docker stop sc-imaging-app-test || true
    - docker stop sc-imaging-container-test || true 
    - docker rmi shakecast/imaging
